### ISSUE TITLE
Build failure on Slackware-Current with upower 0.9.23

### ISSUE THREAD

**Issue by willysr** [linuxmint/cinnamon-settings-daemon#258]
```
Slackware-Current 64 bit
 ```

**Issue**
On Slackware-current, upower is still 0.9.23 and it failed to build properly with an error message:
UP_DEVICE_LEVEL_NONE undeclared

this is introduced in this commit https://github.com/linuxmint/cinnamon-settings-daemon/commit/4842c2d8013577ff323732f0a384815a4a150afa

**Steps to reproduce**
compile cinnamon-settings-daemon as normal

**Expected behaviour**
build normally

**Other information**

**Comment by leigh123linux** [comment]
Why can slackware update upowe?r, why should we continue to support old upower?

**Comment by clefebvre** [comment]
hi @willysr, 

It looks like levels are new in upower 0.99.0: https://github.com/freedesktop/upower/commit/5423adab8902eb22ebebcb60c8b4223ef5d7f3eb.

pinging @mtwebster.

**Comment by clefebvre** [comment]
@willysr if you revert this commit, does it build?

I don't understand how even "UpDeviceLevel" would build at all on upower 0.9.23...

**Comment by clefebvre** [comment]
@leigh123linux updating upower isn't that simple, the new version is missing half the functionality the old one had, you can't simply just upgrade it on its own.

**Comment by leigh123linux** [comment]
@clefebvre I know that updating upower requires a mass package rebuild.
 I don't see why slack can't use old cinnamon-settings-daemon or just use a patch to revert that commit.

**Comment by clefebvre** [comment]
If it's just that commit, it should be pretty easy to fix. If it's the entire level thing, we might need to ifdef a little more.

**Comment by clefebvre** [comment]
@willysr what's the latest stable version of Cinnamon Slackware had? I'm confused, because I see upower batterylevel code (which shouldn't work with old upower) in Cinnamon 4.0 already..

**Comment by mtwebster** [comment]
Please let me know if for some reason that fix doesn't work.  Thanks

**Comment by willysr** [comment]
@clefebvre : we had 4.0 built for Slackware-Current since i had this line before
`sed -i "s|UpDeviceLevel battery_level|UpDeviceClass battery_level|g" plugins/power/csd-power-manager.c`

when i tried to upgrade to 4.2.0, i had problem with this issue since support for old UPower was removed

@mtwebster i got another error after applying that commit:
incompatible types when assigning to type UpDeviceClass in csd-power-manager.c

if i remove the sed part, i got an error message that UpDeviceLevel is unknown type name.

**Comment by mtwebster** [comment]
Change this line:
https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/power/csd-power-manager.c#L4433
to:
`gint battery_level;`

**Comment by willysr** [comment]
@mtwebster that fixed it.
Thanks
